//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EGCMD.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEGCMDListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class EGCMDBaseListener : IEGCMDListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] EGCMDParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] EGCMDParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] EGCMDParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] EGCMDParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] EGCMDParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] EGCMDParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.repeatCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatCommand([NotNull] EGCMDParser.RepeatCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.repeatCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatCommand([NotNull] EGCMDParser.RepeatCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.writeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWriteCommand([NotNull] EGCMDParser.WriteCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.writeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWriteCommand([NotNull] EGCMDParser.WriteCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.setColorCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetColorCommand([NotNull] EGCMDParser.SetColorCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.setColorCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetColorCommand([NotNull] EGCMDParser.SetColorCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EGCMDParser.jsCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsCommand([NotNull] EGCMDParser.JsCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EGCMDParser.jsCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsCommand([NotNull] EGCMDParser.JsCommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
