//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> SingleCarUsageAmount { get; set; }
        public Nullable<decimal> DailyProduction { get; set; }
        public string DefaultSingleBoxPackagingBoxType { get; set; }
        public Nullable<decimal> DefaultSingleBoxLength { get; set; }
        public Nullable<decimal> DefaultSingleBoxWidth { get; set; }
        public Nullable<decimal> DefaultSingleBoxHeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxSNP { get; set; }
        public Nullable<decimal> DefaultSingleBoxRatedMinimumBoxCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxWeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxLayerCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxStorageCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxTheoreticalLayerCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxTheoreticalStorageHeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxThroreticalStorageCount { get; set; }
        public string DefaultOuterPackingPhotoIndex { get; set; }
        public string DefaultOuterPackingBoxType { get; set; }
        public Nullable<decimal> DefaultOuterPackingLength { get; set; }
        public Nullable<decimal> DefaultOuterPackingWidth { get; set; }
        public Nullable<decimal> DefaultOuterPackingHeight { get; set; }
        public string DefaultOuterPackingSNP { get; set; }
        public string DefaultOuterPackingComment { get; set; }
        public Nullable<decimal> DefaultOuterPackingRequiredLayers { get; set; }
        public string DefaultShipmentInfoBoxType { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxLength { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxWidth { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxHeight { get; set; }
        public string DefaultReceiptUnit { get; set; }
        public Nullable<decimal> DefaultReceiptUnitAmount { get; set; }
        public string DefaultShipmentUnit { get; set; }
        public Nullable<decimal> DefaultShipmentUnitAmount { get; set; }
    }
}
