//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentSingleBoxTranPackingInfo
    {
        public int ID { get; set; }
        public int ComponentID { get; set; }
        public string PhotoIndex { get; set; }
        public string PackagingBoxType { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> SNP { get; set; }
        public Nullable<decimal> RatedMinimumBoxCount { get; set; }
        public Nullable<decimal> SingleBoxWeight { get; set; }
        public Nullable<decimal> LayerCount { get; set; }
        public Nullable<decimal> StorageCount { get; set; }
        public Nullable<decimal> TheoreticalLayerCount { get; set; }
        public Nullable<decimal> TheoreticalStorageHeight { get; set; }
        public Nullable<decimal> ThroreticalStorageCount { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
