//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentShipmentInfo
    {
        public int ID { get; set; }
        public int ComponentID { get; set; }
        public string BoxType { get; set; }
        public Nullable<decimal> BoxLength { get; set; }
        public Nullable<decimal> BoxWidth { get; set; }
        public Nullable<decimal> BoxHeight { get; set; }
        public Nullable<decimal> UnitAmount { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
