//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public Component()
        {
            this.ComponentShipmentInfo = new HashSet<ComponentShipmentInfo>();
            this.ComponentOuterPackingSize = new HashSet<ComponentOuterPackingSize>();
            this.ComponentSingleBoxTranPackingInfo = new HashSet<ComponentSingleBoxTranPackingInfo>();
        }
    
        public int ID { get; set; }
        public string ContainerNo { get; set; }
        public string Factroy { get; set; }
        public string WorkPosition { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string SupplierType { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Category { get; set; }
        public string GroupPrincipal { get; set; }
        public Nullable<decimal> SingleCarUsageAmount { get; set; }
        public Nullable<decimal> Charge1 { get; set; }
        public Nullable<decimal> Charge2 { get; set; }
        public Nullable<decimal> InventoryRequirement1Day { get; set; }
        public Nullable<decimal> InventoryRequirement3Day { get; set; }
        public Nullable<decimal> InventoryRequirement5Day { get; set; }
        public Nullable<decimal> InventoryRequirement10Day { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
    
        public virtual ICollection<ComponentShipmentInfo> ComponentShipmentInfo { get; set; }
        public virtual ICollection<ComponentOuterPackingSize> ComponentOuterPackingSize { get; set; }
        public virtual ICollection<ComponentSingleBoxTranPackingInfo> ComponentSingleBoxTranPackingInfo { get; set; }
        public virtual Project Project { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
