//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int ID { get; set; }
        public int WarehouseID { get; set; }
        public int SupplierID { get; set; }
        public string ContainerNo { get; set; }
        public string Factroy { get; set; }
        public string WorkPosition { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string SupplierType { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Category { get; set; }
        public string GroupPrincipal { get; set; }
        public Nullable<decimal> SingleCarUsageAmount { get; set; }
        public Nullable<decimal> ChargeBelow50000 { get; set; }
        public Nullable<decimal> ChargeAbove50000 { get; set; }
        public Nullable<decimal> InventoryRequirement1Day { get; set; }
        public Nullable<decimal> InventoryRequirement3Day { get; set; }
        public Nullable<decimal> InventoryRequirement5Day { get; set; }
        public Nullable<decimal> InventoryRequirement10Day { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
