//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComponentStatistics
    {
        public int ID { get; set; }
        public int ComponentID { get; set; }
        public string SupplierName { get; set; }
        public string ComponentName { get; set; }
        public string ComponentNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> JanSendOut { get; set; }
        public Nullable<decimal> FebSendOut { get; set; }
        public Nullable<decimal> MarSendOut { get; set; }
        public Nullable<decimal> AprSendOut { get; set; }
        public Nullable<decimal> MaySendOut { get; set; }
        public Nullable<decimal> JunSendOut { get; set; }
        public Nullable<decimal> JulSendOut { get; set; }
        public Nullable<decimal> AugSendOut { get; set; }
        public Nullable<decimal> SeptSendOut { get; set; }
        public Nullable<decimal> OctSendOut { get; set; }
        public Nullable<decimal> NovSendOut { get; set; }
        public Nullable<decimal> DecSendOut { get; set; }
        public Nullable<decimal> JanReceive { get; set; }
        public Nullable<decimal> FebReceive { get; set; }
        public Nullable<decimal> MarReceive { get; set; }
        public Nullable<decimal> AprReceive { get; set; }
        public Nullable<decimal> MayReceive { get; set; }
        public Nullable<decimal> JunReceive { get; set; }
        public Nullable<decimal> JulReceive { get; set; }
        public Nullable<decimal> AugReceive { get; set; }
        public Nullable<decimal> SeptReceive { get; set; }
        public Nullable<decimal> OctReceive { get; set; }
        public Nullable<decimal> NovReceive { get; set; }
        public Nullable<decimal> DecReceive { get; set; }
        public Nullable<decimal> JanSendOutFrequency { get; set; }
        public Nullable<decimal> FebSendOutFrequency { get; set; }
        public Nullable<decimal> MarSendOutFrequency { get; set; }
        public Nullable<decimal> AprSendOutFrequency { get; set; }
        public Nullable<decimal> MaySendOutFrequency { get; set; }
        public Nullable<decimal> JunSendOutFrequency { get; set; }
        public Nullable<decimal> JulSendOutFrequency { get; set; }
        public Nullable<decimal> AugSendOutFrequency { get; set; }
        public Nullable<decimal> SeptSendOutFrequency { get; set; }
        public Nullable<decimal> OctSendOutFrequency { get; set; }
        public Nullable<decimal> NovSendOutFrequency { get; set; }
        public Nullable<decimal> DecSendOutFrequency { get; set; }
        public Nullable<decimal> JanSendOutAvg { get; set; }
        public Nullable<decimal> FebSendOutAvg { get; set; }
        public Nullable<decimal> MarSendOutAvg { get; set; }
        public Nullable<decimal> AprSendOutAvg { get; set; }
        public Nullable<decimal> MaySendOutAvg { get; set; }
        public Nullable<decimal> JunSendOutAvg { get; set; }
        public Nullable<decimal> JulSendOutAvg { get; set; }
        public Nullable<decimal> AugSendOutAvg { get; set; }
        public Nullable<decimal> SeptSendOutAvg { get; set; }
        public Nullable<decimal> OctSendOutAvg { get; set; }
        public Nullable<decimal> NovSendOutAvg { get; set; }
        public Nullable<decimal> DecSendOutAvg { get; set; }
        public Nullable<decimal> JanReceiveAvg { get; set; }
        public Nullable<decimal> FebReceiveAvg { get; set; }
        public Nullable<decimal> MarReceiveAvg { get; set; }
        public Nullable<decimal> AprReceiveAvg { get; set; }
        public Nullable<decimal> MayReceiveAvg { get; set; }
        public Nullable<decimal> JunReceiveAvg { get; set; }
        public Nullable<decimal> JulReceiveAvg { get; set; }
        public Nullable<decimal> AugReceiveAvg { get; set; }
        public Nullable<decimal> SeptReceiveAvg { get; set; }
        public Nullable<decimal> OctReceiveAvg { get; set; }
        public Nullable<decimal> NovReceiveAvg { get; set; }
        public Nullable<decimal> DecReceiveAvg { get; set; }
        public Nullable<decimal> JanReceiveFrequency { get; set; }
        public Nullable<decimal> FebReceiveFrequency { get; set; }
        public Nullable<decimal> MarReceiveFrequency { get; set; }
        public Nullable<decimal> AprReceiveFrequency { get; set; }
        public Nullable<decimal> MayReceiveFrequency { get; set; }
        public Nullable<decimal> JunReceiveFrequency { get; set; }
        public Nullable<decimal> JulReceiveFrequency { get; set; }
        public Nullable<decimal> AugReceiveFrequency { get; set; }
        public Nullable<decimal> SeptReceiveFrequency { get; set; }
        public Nullable<decimal> OctReceiveFrequency { get; set; }
        public Nullable<decimal> NovReceiveFrequency { get; set; }
        public Nullable<decimal> DecReceiveFrequency { get; set; }
        public Nullable<decimal> JanMaxStock { get; set; }
        public Nullable<decimal> FebMaxStock { get; set; }
        public Nullable<decimal> MarMaxStock { get; set; }
        public Nullable<decimal> AprMaxStock { get; set; }
        public Nullable<decimal> MayMaxStock { get; set; }
        public Nullable<decimal> JunMaxStock { get; set; }
        public Nullable<decimal> JulMaxStock { get; set; }
        public Nullable<decimal> AugMaxStock { get; set; }
        public Nullable<decimal> SeptMaxStock { get; set; }
        public Nullable<decimal> OctMaxStock { get; set; }
        public Nullable<decimal> NovMaxStock { get; set; }
        public Nullable<decimal> DecMaxStock { get; set; }
        public Nullable<decimal> JanServiceCharge { get; set; }
        public Nullable<decimal> FebServiceCharge { get; set; }
        public Nullable<decimal> MarServiceCharge { get; set; }
        public Nullable<decimal> AprServiceCharge { get; set; }
        public Nullable<decimal> MayServiceCharge { get; set; }
        public Nullable<decimal> JunServiceCharge { get; set; }
        public Nullable<decimal> JulServiceCharge { get; set; }
        public Nullable<decimal> AugServiceCharge { get; set; }
        public Nullable<decimal> SeptServiceCharge { get; set; }
        public Nullable<decimal> OctServiceCharge { get; set; }
        public Nullable<decimal> NovServiceCharge { get; set; }
        public Nullable<decimal> DecServiceCharge { get; set; }
    
        public virtual Component Component { get; set; }
    }
}
