//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTicketItem
    {
        public int ID { get; set; }
        public int JobTickedID { get; set; }
        public Nullable<int> StockInfoID { get; set; }
        public string No { get; set; }
        public string Type { get; set; }
        public string MoveOutStorageLocation { get; set; }
        public string SourceBoardNo { get; set; }
        public string MoveInStorageLocation { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ScheduledMoveCount { get; set; }
        public Nullable<decimal> MoveCount { get; set; }
        public Nullable<decimal> HaveBackedCount { get; set; }
        public string ActualJobPerson { get; set; }
        public Nullable<System.DateTime> HappenTime { get; set; }
    
        public virtual JobTicket JobTicket { get; set; }
    }
}
