//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTicketItem
    {
        public int ID { get; set; }
        public int WarehouseID { get; set; }
        public string No { get; set; }
        public string Type { get; set; }
        public string MoveOutStorageLocation { get; set; }
        public string SourceBoardNo { get; set; }
        public string MoveInStorageLocation { get; set; }
        public int ComponentID { get; set; }
        public string ComponentNo { get; set; }
        public string ComponentName { get; set; }
        public string PackagingUnit { get; set; }
        public Nullable<decimal> ScheduledMoveCount { get; set; }
        public Nullable<decimal> MoveCount { get; set; }
        public Nullable<decimal> HaveBackedCount { get; set; }
        public string StockState { get; set; }
        public string ExecuteState { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public string ReceiptNo { get; set; }
        public string ManufactureNo { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> NearEffectDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ProjectInfo { get; set; }
        public string ProjectPhaseInfo { get; set; }
        public string RealRightProperty { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public string Supplier { get; set; }
        public string ActualJobPerson { get; set; }
        public Nullable<System.DateTime> HappenTime { get; set; }
    
        public virtual Component Component { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
