//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTicket
    {
        public JobTicket()
        {
            this.JobTicketItem = new HashSet<JobTicketItem>();
            this.PutOutStorageTicket = new HashSet<PutOutStorageTicket>();
        }
    
        public int ID { get; set; }
        public string JobTicketNo { get; set; }
        public string JobType { get; set; }
        public string JobGroupName { get; set; }
        public Nullable<decimal> ScheduledAmount { get; set; }
        public Nullable<decimal> RealAmount { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> PrintedTimes { get; set; }
        public string AssignmentArea { get; set; }
        public string PersonInCharge { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public int ShipmentTicketID { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<JobTicketItem> JobTicketItem { get; set; }
        public virtual User User1 { get; set; }
        public virtual ShipmentTicket ShipmentTicket { get; set; }
        public virtual ICollection<PutOutStorageTicket> PutOutStorageTicket { get; set; }
    }
}
