//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTicketItemView
    {
        public int ID { get; set; }
        public int JobTicketID { get; set; }
        public Nullable<int> StockInfoID { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> HappenTime { get; set; }
        public Nullable<int> ReceiptTicketItemComponentID { get; set; }
        public string SupplierName { get; set; }
        public string JobTicketJobTicketNo { get; set; }
        public Nullable<int> ReceiptTicketItemReceiptTicketID { get; set; }
        public string ComponentNo { get; set; }
        public string ComponentNumber { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> ComponentProjectID { get; set; }
        public Nullable<int> ComponentWarehouseID { get; set; }
        public string SupplierNumber { get; set; }
        public string JobPersonName { get; set; }
        public string ConfirmPersonName { get; set; }
    }
}
