//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTicketView
    {
        public int JobTicketID { get; set; }
        public int JobTicketShipmentTicketID { get; set; }
        public string JobTicketJobTicketNo { get; set; }
        public string JobTicketJobType { get; set; }
        public string JobTicketJobGroupName { get; set; }
        public Nullable<decimal> JobTicketScheduledAmount { get; set; }
        public Nullable<decimal> JobTicketRealAmount { get; set; }
        public string JobTicketState { get; set; }
        public Nullable<int> JobTicketPrintedTimes { get; set; }
        public string JobTicketAssignmentArea { get; set; }
        public string JobTicketPersonInCharge { get; set; }
        public int JobTicketCreateUserID { get; set; }
        public Nullable<System.DateTime> JobTicketCreateTime { get; set; }
        public Nullable<int> JobTicketLastUpdateUserID { get; set; }
        public Nullable<System.DateTime> JobTicketLastUpdateTime { get; set; }
        public Nullable<int> ShipmentTicketProjectID { get; set; }
        public Nullable<int> ShipmentTicketWarehouseID { get; set; }
        public string ShipmentTicketNo { get; set; }
        public string ShipmentTicketType { get; set; }
        public string ShipmentTicketTypeNo { get; set; }
        public string ShipmentTicketSource { get; set; }
        public Nullable<decimal> ShipmentTicketSegmentationChainCount { get; set; }
        public string ShipmentTicketRelatedTicketNo { get; set; }
        public Nullable<System.DateTime> ShipmentTicketDate { get; set; }
        public Nullable<int> ShipmentTicketTicketNum { get; set; }
        public Nullable<System.DateTime> ShipmentTicketRequireArriveDate { get; set; }
        public string ShipmentTicketState { get; set; }
        public Nullable<decimal> ShipmentTicketScheduledAmount { get; set; }
        public Nullable<decimal> ShipmentTicketAllocatedAmount { get; set; }
        public Nullable<decimal> ShipmentTicketPickingAmount { get; set; }
        public Nullable<decimal> ShipmentTicketShipmentAmount { get; set; }
        public Nullable<decimal> ShipmentTicketExceedStorageAmount { get; set; }
        public string ShipmentTicketStation { get; set; }
        public string ShipmentTicketReverseTicketNo { get; set; }
        public string ShipmentTicketSortType { get; set; }
        public string ShipmentTicketProductionLine { get; set; }
        public string ShipmentTicketReceivingPersonName { get; set; }
        public string ShipmentTicketContactAddress { get; set; }
        public string ShipmentTicketDeliveryPath { get; set; }
        public string ShipmentTicketDescription { get; set; }
        public string ShipmentTicketCloseReason { get; set; }
        public Nullable<int> ShipmentTicketCreateUserID { get; set; }
        public Nullable<System.DateTime> ShipmentTicketCreateTime { get; set; }
        public Nullable<int> ShipmentTicketLastUpdateUserID { get; set; }
        public Nullable<System.DateTime> ShipmentTicketLastUpdateTime { get; set; }
        public Nullable<int> ShipmentTicketPrintTimes { get; set; }
        public Nullable<int> ShipmentTicketWaitingToBeDone { get; set; }
        public string ShipmentTicketDeliveryTicketNo { get; set; }
        public string ShipmentTicketOuterPhysicalDistributionPath { get; set; }
        public string ShipmentTicketDeliveryPoint { get; set; }
        public Nullable<int> ShipmentTicketEmergency { get; set; }
        public string ShipmentTicketShipmentPlaceNo { get; set; }
        public Nullable<int> ShipmentTicketBoardPrintedTimes { get; set; }
        public string ProjectName { get; set; }
        public string WarehouseName { get; set; }
        public string CreateUserUsername { get; set; }
        public string CreateUserPassword { get; set; }
        public Nullable<int> CreateUserAuthority { get; set; }
        public string CreateUserAuthorityName { get; set; }
        public Nullable<int> CreateUserSupplierID { get; set; }
        public string LastUpdateUserUsername { get; set; }
        public string LastUpdateUserPassword { get; set; }
        public Nullable<int> LastUpdateUserAuthority { get; set; }
        public string LastUpdateUserAuthorityName { get; set; }
        public Nullable<int> LastUpdateUserSupplierID { get; set; }
    }
}
