//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Component = new HashSet<Component>();
            this.JobTicket = new HashSet<JobTicket>();
            this.PutawayTicket = new HashSet<PutawayTicket>();
            this.PutOutStorageTicket = new HashSet<PutOutStorageTicket>();
            this.ShipmentTicket = new HashSet<ShipmentTicket>();
            this.StockInfo = new HashSet<StockInfo>();
            this.StockInfoCheckTicket = new HashSet<StockInfoCheckTicket>();
            this.SubmissionTicket = new HashSet<SubmissionTicket>();
            this.ReceiptTicket = new HashSet<ReceiptTicket>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Component> Component { get; set; }
        public virtual ICollection<JobTicket> JobTicket { get; set; }
        public virtual ICollection<PutawayTicket> PutawayTicket { get; set; }
        public virtual ICollection<PutOutStorageTicket> PutOutStorageTicket { get; set; }
        public virtual ICollection<ShipmentTicket> ShipmentTicket { get; set; }
        public virtual ICollection<StockInfo> StockInfo { get; set; }
        public virtual ICollection<StockInfoCheckTicket> StockInfoCheckTicket { get; set; }
        public virtual ICollection<SubmissionTicket> SubmissionTicket { get; set; }
        public virtual ICollection<ReceiptTicket> ReceiptTicket { get; set; }
    }
}
