//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutawayTicket
    {
        public PutawayTicket()
        {
            this.PutawayTicketItem = new HashSet<PutawayTicketItem>();
        }
    
        public int ID { get; set; }
        public string No { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public int ReceiptTicketID { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ScheduledDisplacementAmount { get; set; }
        public Nullable<decimal> DisplacementAmount { get; set; }
        public Nullable<decimal> DistributeAmount { get; set; }
        public Nullable<decimal> PrintTimes { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string JobGroupName { get; set; }
        public string LastUpdateUserName { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<PutawayTicketItem> PutawayTicketItem { get; set; }
    }
}
