//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutawayTicketView
    {
        public int ID { get; set; }
        public string No { get; set; }
        public string Type { get; set; }
        public Nullable<int> ReceiptTicketID { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ScheduledDisplacementAmount { get; set; }
        public Nullable<decimal> DisplacementAmount { get; set; }
        public Nullable<decimal> DistributeAmount { get; set; }
        public Nullable<decimal> PrintTimes { get; set; }
        public string JobGroupName { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string CreateUserUsername { get; set; }
        public string CreateUserPassword { get; set; }
        public Nullable<int> CreateUserAuthority { get; set; }
        public string CreateUserAuthorityName { get; set; }
        public Nullable<int> CreateUserSupplierID { get; set; }
        public string LastUpdateUserUsername { get; set; }
        public string LastUpdateUserPassword { get; set; }
        public Nullable<int> LastUpdateUserAuthority { get; set; }
        public string LastUpdateUserAuthorityName { get; set; }
        public Nullable<int> LastUpdateUserSupplierID { get; set; }
        public string ProjectName { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ReceiptTicketState { get; set; }
        public string ReceiptTicketNo { get; set; }
        public string ReceiptTicketNumber { get; set; }
        public string SupplierNumber { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string PersonName { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<System.DateTime> ReceiptTicketReceiptDate { get; set; }
        public string InwardDeliverTicketNo { get; set; }
    }
}
