//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutawayTicket
    {
        public PutawayTicket()
        {
            this.PutawayTicketComponentInfo = new HashSet<PutawayTicketComponentInfo>();
        }
    
        public int ID { get; set; }
        public string No { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> TicketCreateTime { get; set; }
        public string ReceiptTicketNo { get; set; }
        public int ReceiptTicketID { get; set; }
        public string State { get; set; }
        public Nullable<decimal> ScheduledDisplacementAmount { get; set; }
        public Nullable<decimal> DisplacementAmount { get; set; }
        public Nullable<decimal> DistributeAmount { get; set; }
        public Nullable<decimal> PrintTimes { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string JobGroupName { get; set; }
        public string LastOperatorName { get; set; }
    
        public virtual ICollection<PutawayTicketComponentInfo> PutawayTicketComponentInfo { get; set; }
    }
}
