//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfoCheckTicketItemView
    {
        public int ID { get; set; }
        public Nullable<int> StockInfoID { get; set; }
        public Nullable<decimal> ExcpetedOverflowAreaAmount { get; set; }
        public Nullable<decimal> ExpectedShipmentAreaAmount { get; set; }
        public Nullable<decimal> RealOverflowAreaAmount { get; set; }
        public Nullable<decimal> RealShipmentAreaAmount { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> StockInfoCheckTicketID { get; set; }
        public string No { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Expr1 { get; set; }
    }
}
