//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfoView
    {
        public int ID { get; set; }
        public Nullable<int> ReceiptTicketItemID { get; set; }
        public Nullable<decimal> OverflowAreaAmount { get; set; }
        public Nullable<decimal> ReceiptAreaAmount { get; set; }
        public Nullable<decimal> ShipmentAreaAmount { get; set; }
        public string ReceiptTicketItemPackageName { get; set; }
        public Nullable<decimal> ReceiptTicketItemExpectedPackageAmount { get; set; }
        public Nullable<decimal> ReceiptTicketItemExpectedAmount { get; set; }
        public Nullable<decimal> ReceiptTicketItemReceiviptAmount { get; set; }
        public Nullable<decimal> ReceiptTicketItemWrongComponentAmount { get; set; }
        public Nullable<decimal> ReceiptTicketItemShortageAmount { get; set; }
        public Nullable<decimal> ReceiptTicketItemDisqualifiedAmount { get; set; }
        public Nullable<int> ReceiptTicketSupplierID { get; set; }
        public string SupplierName { get; set; }
        public string ComponentName { get; set; }
        public string ProjectName { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<decimal> RejectAreaAmount { get; set; }
        public Nullable<decimal> SubmissionAmount { get; set; }
        public string ReceiptTicketItemState { get; set; }
        public Nullable<int> ReceiptTicketItemReceiptTicketID { get; set; }
        public string ReceiptTicketState { get; set; }
        public string ReceiptTicketNo { get; set; }
        public string ReceiptTicketNumber { get; set; }
        public string SupplierNumber { get; set; }
        public Nullable<System.DateTime> ReceiptTicketItemManufactureDate { get; set; }
        public Nullable<System.DateTime> ReceiptTicketItemExpiryDate { get; set; }
        public Nullable<System.DateTime> ReceiptTicketItemInventoryDate { get; set; }
        public string SupplyNumber { get; set; }
        public string SupplyNo { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ManufactureDate { get; set; }
        public Nullable<System.DateTime> InventoryDate { get; set; }
        public Nullable<int> SupplyID { get; set; }
    }
}
