//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionTicket
    {
        public SubmissionTicket()
        {
            this.SubmissionTicketItem = new HashSet<SubmissionTicketItem>();
        }
    
        public int ID { get; set; }
        public int ReceiptTicketID { get; set; }
        public string InwardDeliverTicketNo { get; set; }
        public string CreateDate { get; set; }
        public string No { get; set; }
        public string SAPNo { get; set; }
        public string ManufatureName { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> HasSelfInspectionReport { get; set; }
        public string CreatePerson { get; set; }
        public string DeliverSubmissionPerson { get; set; }
        public string ReceivePerson { get; set; }
        public string SubmissionPerson { get; set; }
        public string Result { get; set; }
    
        public virtual ReceiptTicket ReceiptTicket { get; set; }
        public virtual ICollection<SubmissionTicketItem> SubmissionTicketItem { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
