//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionTicketItemView
    {
        public int ID { get; set; }
        public int SubmissionTicketID { get; set; }
        public string LineItem { get; set; }
        public string State { get; set; }
        public Nullable<int> ReceiptTicketItemID { get; set; }
        public Nullable<decimal> ArriveAmount { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> SubmissionAmount { get; set; }
        public Nullable<decimal> ReturnAmount { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SubmissionReceiptTicketID { get; set; }
        public string SupplierName { get; set; }
        public string ProjectName { get; set; }
        public string WarehouseName { get; set; }
        public string CreateUserUsername { get; set; }
        public string CreateUserPassword { get; set; }
        public Nullable<int> CreateUserAuthority { get; set; }
        public string CreateUserAuthorityName { get; set; }
        public Nullable<int> CreateUserSupplierID { get; set; }
        public string LastUpdateUserUsername { get; set; }
        public string LastUpdateUserPassword { get; set; }
        public Nullable<int> LastUpdateUserAuthority { get; set; }
        public string LastUpdateUserAuthorityName { get; set; }
        public Nullable<int> LastUpdateUserSupplierID { get; set; }
        public string ComponentNo { get; set; }
        public string ComponentName { get; set; }
        public Nullable<int> ReceiptTicketWarehouse { get; set; }
        public string ReceiptTicketNo { get; set; }
        public Nullable<int> ReceiptTicketSupplierID { get; set; }
        public string ReceiptTicketItemState { get; set; }
        public Nullable<int> ReceiptTicketItemComponentID { get; set; }
        public string SubmissionTicketNo { get; set; }
        public string SubmissionTicketState { get; set; }
        public string ReceiptTicketState { get; set; }
        public Nullable<int> ReceiptTicketProjectID { get; set; }
        public string ReceiptTicketNumber { get; set; }
        public string SupplierNumber { get; set; }
        public string ComponentComponent { get; set; }
        public Nullable<int> JobPersonID { get; set; }
        public Nullable<int> ConfirmPersonID { get; set; }
        public string JobPersonName { get; set; }
        public string ConfirmPersonName { get; set; }
    }
}
