//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAnnualInfo
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> ContractArea { get; set; }
        public Nullable<decimal> NetArea { get; set; }
        public Nullable<decimal> FixedStorageCost { get; set; }
        public Nullable<decimal> JanAreaIncreasement { get; set; }
        public Nullable<decimal> FebAreaIncreasement { get; set; }
        public Nullable<decimal> MarAreaIncreasement { get; set; }
        public Nullable<decimal> AprAreaIncreasement { get; set; }
        public Nullable<decimal> MayAreaIncreasement { get; set; }
        public Nullable<decimal> JunAreaIncreasement { get; set; }
        public Nullable<decimal> JulAreaIncreasement { get; set; }
        public Nullable<decimal> AugAreaIncreasement { get; set; }
        public Nullable<decimal> SeptAreaIncreasement { get; set; }
        public Nullable<decimal> OctAreaIncreasement { get; set; }
        public Nullable<decimal> NovAreaIncreasement { get; set; }
        public Nullable<decimal> DecAreaIncreasement { get; set; }
        public Nullable<decimal> JanStorageDays { get; set; }
        public Nullable<decimal> FebStorageDays { get; set; }
        public Nullable<decimal> MarStorageDays { get; set; }
        public Nullable<decimal> AprStorageDays { get; set; }
        public Nullable<decimal> MayStorageDays { get; set; }
        public Nullable<decimal> JunStorageDays { get; set; }
        public Nullable<decimal> JulStorageDays { get; set; }
        public Nullable<decimal> AugStorageDays { get; set; }
        public Nullable<decimal> SeptStorageDays { get; set; }
        public Nullable<decimal> OctStorageDays { get; set; }
        public Nullable<decimal> NovStorageDays { get; set; }
        public Nullable<decimal> DecStorageDays { get; set; }
        public Nullable<decimal> JanStorageFee { get; set; }
        public Nullable<decimal> FebStorageFee { get; set; }
        public Nullable<decimal> MarStorageFee { get; set; }
        public Nullable<decimal> AprStorageFee { get; set; }
        public Nullable<decimal> MayStorageFee { get; set; }
        public Nullable<decimal> JunStorageFee { get; set; }
        public Nullable<decimal> JulStorageFee { get; set; }
        public Nullable<decimal> AugStorageFee { get; set; }
        public Nullable<decimal> SeptStorageFee { get; set; }
        public Nullable<decimal> OctStorageFee { get; set; }
        public Nullable<decimal> NovStorageFee { get; set; }
        public Nullable<decimal> DecStorageFee { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
