//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierAnnualInfoView
    {
        public int ID { get; set; }
        public int SupplierID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> NetArea { get; set; }
        public Nullable<decimal> FixedStorageCost { get; set; }
        public Nullable<decimal> JanContractArea { get; set; }
        public Nullable<decimal> FebContractArea { get; set; }
        public Nullable<decimal> MarContractArea { get; set; }
        public Nullable<decimal> AprContractArea { get; set; }
        public Nullable<decimal> MayContractArea { get; set; }
        public Nullable<decimal> JunContractArea { get; set; }
        public Nullable<decimal> JulContractArea { get; set; }
        public Nullable<decimal> AugContractArea { get; set; }
        public Nullable<decimal> SeptContractArea { get; set; }
        public Nullable<decimal> OctContractArea { get; set; }
        public Nullable<decimal> NovContractArea { get; set; }
        public Nullable<decimal> DecContractArea { get; set; }
        public Nullable<decimal> JanAreaIncreasement { get; set; }
        public Nullable<decimal> FebAreaIncreasement { get; set; }
        public Nullable<decimal> MarAreaIncreasement { get; set; }
        public Nullable<decimal> AprAreaIncreasement { get; set; }
        public Nullable<decimal> MayAreaIncreasement { get; set; }
        public Nullable<decimal> JunAreaIncreasement { get; set; }
        public Nullable<decimal> JulAreaIncreasement { get; set; }
        public Nullable<decimal> AugAreaIncreasement { get; set; }
        public Nullable<decimal> SeptAreaIncreasement { get; set; }
        public Nullable<decimal> OctAreaIncreasement { get; set; }
        public Nullable<decimal> NovAreaIncreasement { get; set; }
        public Nullable<decimal> DecAreaIncreasement { get; set; }
        public Nullable<decimal> JanStorageDays { get; set; }
        public Nullable<decimal> FebStorageDays { get; set; }
        public Nullable<decimal> MarStorageDays { get; set; }
        public Nullable<decimal> AprStorageDays { get; set; }
        public Nullable<decimal> MayStorageDays { get; set; }
        public Nullable<decimal> JunStorageDays { get; set; }
        public Nullable<decimal> JulStorageDays { get; set; }
        public Nullable<decimal> AugStorageDays { get; set; }
        public Nullable<decimal> SeptStorageDays { get; set; }
        public Nullable<decimal> OctStorageDays { get; set; }
        public Nullable<decimal> NovStorageDays { get; set; }
        public Nullable<decimal> DecStorageDays { get; set; }
        public Nullable<decimal> JanStorageFee { get; set; }
        public Nullable<decimal> FebStorageFee { get; set; }
        public Nullable<decimal> MarStorageFee { get; set; }
        public Nullable<decimal> AprStorageFee { get; set; }
        public Nullable<decimal> MayStorageFee { get; set; }
        public Nullable<decimal> JunStorageFee { get; set; }
        public Nullable<decimal> JulStorageFee { get; set; }
        public Nullable<decimal> AugStorageFee { get; set; }
        public Nullable<decimal> SeptStorageFee { get; set; }
        public Nullable<decimal> OctStorageFee { get; set; }
        public Nullable<decimal> NovStorageFee { get; set; }
        public Nullable<decimal> DecStorageFee { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContractNo { get; set; }
        public Nullable<System.DateTime> SupplierStartDate { get; set; }
        public Nullable<System.DateTime> SupplierEndDate { get; set; }
        public Nullable<System.DateTime> SupplierInvoiceDate { get; set; }
        public Nullable<System.DateTime> SupplierBalanceDate { get; set; }
        public string SupplierFullName { get; set; }
        public string SupplierTaxpayerNumber { get; set; }
        public string SupplierAddress { get; set; }
        public string SupplierTel { get; set; }
        public string SupplierBankName { get; set; }
        public string SupplierBankAccount { get; set; }
        public string SupplierBankNo { get; set; }
        public string SupplierZipCode { get; set; }
        public string SupplierRecipientName { get; set; }
    }
}
