//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyView
    {
        public int ID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ComponentID { get; set; }
        public string Number { get; set; }
        public string PhotoIndex { get; set; }
        public string ContainerNo { get; set; }
        public string Factroy { get; set; }
        public string WorkPosition { get; set; }
        public string No { get; set; }
        public string SupplierType { get; set; }
        public string Type { get; set; }
        public string Size { get; set; }
        public string Category { get; set; }
        public string GroupPrincipal { get; set; }
        public Nullable<decimal> Charge1 { get; set; }
        public Nullable<decimal> Charge2 { get; set; }
        public Nullable<int> IsHistory { get; set; }
        public Nullable<int> NewestComponentID { get; set; }
        public Nullable<int> CreateUserID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string SingleBoxPhotoIndex { get; set; }
        public string SingleBoxPackagingBoxType { get; set; }
        public Nullable<decimal> SingleBoxLength { get; set; }
        public Nullable<decimal> SingleBoxWidth { get; set; }
        public Nullable<decimal> SingleBoxHeight { get; set; }
        public Nullable<decimal> SingleBoxSNP { get; set; }
        public Nullable<decimal> SingleBoxRatedMinimumBoxCount { get; set; }
        public Nullable<decimal> SingleBoxWeight { get; set; }
        public Nullable<decimal> SingleBoxLayerCount { get; set; }
        public Nullable<decimal> SingleBoxStorageCount { get; set; }
        public Nullable<decimal> SingleBoxTheoreticalLayerCount { get; set; }
        public Nullable<decimal> SingleBoxTheoreticalStorageHeight { get; set; }
        public Nullable<decimal> SingleBoxThroreticalStorageCount { get; set; }
        public string OuterPackingPhotoIndex { get; set; }
        public string OuterPackingBoxType { get; set; }
        public Nullable<decimal> OuterPackingLength { get; set; }
        public Nullable<decimal> OuterPackingWidth { get; set; }
        public Nullable<decimal> OuterPackingHeight { get; set; }
        public string OuterPackingSNP { get; set; }
        public string OuterPackingComment { get; set; }
        public Nullable<decimal> OuterPackingRequiredLayers { get; set; }
        public string ShipmentInfoBoxType { get; set; }
        public Nullable<decimal> ShipmentInfoBoxLength { get; set; }
        public Nullable<decimal> ShipmentInfoBoxWidth { get; set; }
        public Nullable<decimal> ShipmentInfoBoxHeight { get; set; }
        public Nullable<decimal> ShipmentInfoUnitAmount { get; set; }
        public string ReceiptUnit { get; set; }
        public Nullable<decimal> ReceiptUnitAmount { get; set; }
        public string ShipmentUnit { get; set; }
        public Nullable<decimal> ShipmentUnitAmount { get; set; }
        public string ComponentName { get; set; }
        public Nullable<decimal> SingleCarUsageAmount { get; set; }
        public Nullable<decimal> DailyProduction { get; set; }
        public string DefaultSingleBoxPackagingBoxType { get; set; }
        public Nullable<decimal> DefaultSingleBoxLength { get; set; }
        public Nullable<decimal> DefaultSingleBoxWidth { get; set; }
        public Nullable<decimal> DefaultSingleBoxHeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxSNP { get; set; }
        public Nullable<decimal> DefaultSingleBoxRatedMinimumBoxCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxWeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxLayerCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxStorageCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxTheoreticalLayerCount { get; set; }
        public Nullable<decimal> DefaultSingleBoxTheoreticalStorageHeight { get; set; }
        public Nullable<decimal> DefaultSingleBoxThroreticalStorageCount { get; set; }
        public string DefaultOuterPackingPhotoIndex { get; set; }
        public string DefaultOuterPackingBoxType { get; set; }
        public Nullable<decimal> DefaultOuterPackingLength { get; set; }
        public Nullable<decimal> DefaultOuterPackingWidth { get; set; }
        public Nullable<decimal> DefaultOuterPackingHeight { get; set; }
        public string DefaultOuterPackingSNP { get; set; }
        public string DefaultOuterPackingComment { get; set; }
        public Nullable<decimal> DefaultOuterPackingRequiredLayers { get; set; }
        public string DefaultShipmentInfoBoxType { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxLength { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxWidth { get; set; }
        public Nullable<decimal> DefaultShipmentInfoBoxHeight { get; set; }
        public string DefaultReceiptUnit { get; set; }
        public Nullable<decimal> DefaultReceiptUnitAmount { get; set; }
        public string DefaultShipmentUnit { get; set; }
        public Nullable<decimal> DefaultShipmentUnitAmount { get; set; }
        public string ProjectName { get; set; }
        public string WarehouseName { get; set; }
        public string SupplierName { get; set; }
    }
}
