//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public Warehouse()
        {
            this.Component = new HashSet<Component>();
            this.JobTicket = new HashSet<JobTicket>();
            this.JobTicketItem = new HashSet<JobTicketItem>();
            this.PutInStorageTicketComponentInfo = new HashSet<PutInStorageTicketComponentInfo>();
            this.PutOutStorageTicket = new HashSet<PutOutStorageTicket>();
            this.ReceiptTicket = new HashSet<ReceiptTicket>();
            this.ShipmentTicket = new HashSet<ShipmentTicket>();
            this.Supplier = new HashSet<Supplier>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Component> Component { get; set; }
        public virtual ICollection<JobTicket> JobTicket { get; set; }
        public virtual ICollection<JobTicketItem> JobTicketItem { get; set; }
        public virtual ICollection<PutInStorageTicketComponentInfo> PutInStorageTicketComponentInfo { get; set; }
        public virtual ICollection<PutOutStorageTicket> PutOutStorageTicket { get; set; }
        public virtual ICollection<ReceiptTicket> ReceiptTicket { get; set; }
        public virtual ICollection<ShipmentTicket> ShipmentTicket { get; set; }
        public virtual ICollection<Supplier> Supplier { get; set; }
    }
}
