//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EMacro.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IEMacroListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class EMacroBaseListener : IEMacroListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStat([NotNull] EMacroParser.StatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.stat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStat([NotNull] EMacroParser.StatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommand([NotNull] EMacroParser.CommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.command"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommand([NotNull] EMacroParser.CommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterText([NotNull] EMacroParser.TextContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitText([NotNull] EMacroParser.TextContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.commandStartSharp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandStartSharp([NotNull] EMacroParser.CommandStartSharpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.commandStartSharp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandStartSharp([NotNull] EMacroParser.CommandStartSharpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.commandStartAt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandStartAt([NotNull] EMacroParser.CommandStartAtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.commandStartAt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandStartAt([NotNull] EMacroParser.CommandStartAtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.writeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWriteCommand([NotNull] EMacroParser.WriteCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.writeCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWriteCommand([NotNull] EMacroParser.WriteCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.repeatCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatCommand([NotNull] EMacroParser.RepeatCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.repeatCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatCommand([NotNull] EMacroParser.RepeatCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.setColorCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetColorCommand([NotNull] EMacroParser.SetColorCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.setColorCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetColorCommand([NotNull] EMacroParser.SetColorCommandContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.jsCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJsCommand([NotNull] EMacroParser.JsCommandContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.jsCommand"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJsCommand([NotNull] EMacroParser.JsCommandContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
