//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EMacro.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="EMacroParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IEMacroListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] EMacroParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] EMacroParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommand([NotNull] EMacroParser.CommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommand([NotNull] EMacroParser.CommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] EMacroParser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] EMacroParser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.commandStartSharp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandStartSharp([NotNull] EMacroParser.CommandStartSharpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.commandStartSharp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandStartSharp([NotNull] EMacroParser.CommandStartSharpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.commandStartAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandStartAt([NotNull] EMacroParser.CommandStartAtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.commandStartAt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandStartAt([NotNull] EMacroParser.CommandStartAtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.writeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteCommand([NotNull] EMacroParser.WriteCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.writeCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteCommand([NotNull] EMacroParser.WriteCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.repeatCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatCommand([NotNull] EMacroParser.RepeatCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.repeatCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatCommand([NotNull] EMacroParser.RepeatCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.setColorCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetColorCommand([NotNull] EMacroParser.SetColorCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.setColorCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetColorCommand([NotNull] EMacroParser.SetColorCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.setTableColumnsCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetTableColumnsCommand([NotNull] EMacroParser.SetTableColumnsCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.setTableColumnsCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetTableColumnsCommand([NotNull] EMacroParser.SetTableColumnsCommandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="EMacroParser.jsCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJsCommand([NotNull] EMacroParser.JsCommandContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="EMacroParser.jsCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJsCommand([NotNull] EMacroParser.JsCommandContext context);
}
